### ISSUE TITLE
Change locale sites to use subfolders instead of alternative domains

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#103]
When we first set up the website, we configured it so that each language of the site would have its own domain.

- wemeditate.com -> English
- wemeditate.ru -> Russian
- wemeditate.it -> Italian
- ua.wemeditate.com -> Ukrainian
- cz.wemeditate.com -> Czech
- And so on...

We want to change this so that it will use subfolders instead

- wemeditate.com -> English
- wemeditate.com/ru -> Russian
- wemeditate.com/it -> Italian
- wemeditate.com/ua -> Ukrainian
- wemeditate.com/cz -> Czech
- And so on...

Currently this is managed using a gem called [route_translator](https://github.com/enriclluelles/route_translator) and is configured in [config/initializers/route_config.rb](https://github.com/sydevs/WeMeditate/blob/master/config/initializers/route_config.rb). There may also be some relevant code in [config/routes.rb](https://github.com/sydevs/WeMeditate/blob/master/config/routes.rb), specifically the call to `localized` (which is a function that comes from route_translator)

By default, route_translator actually works in the way that we want to work, using subfolders. But we've instead configured it to use the [Host-based locales approach](https://github.com/enriclluelles/route_translator#host-based-locale). So we should just need to remove the host_locales configuration, and make sure we are configuring everything needed for the basic behaviour.

After this is set up and working, we will configure CloudFlare to redirect the old URLs to the new structure.

**Comment by Ardnived** [comment]
Basically the reason we are doing this is because long term we expect it to improve our search ranking on Google and other search engines.

**Comment by dbackeus** [comment]
Seems like a good idea 👍 

Feel free to ping me if you need any help with Cloudflare etc.

**Comment by Ardnived** [comment]
Great thanks. We could use help setting up redirects from the old domains to the new URLs when it's implemented. We want to make sure that old URLs continue to work with a redirect.

At the moment @Mrinalsinghal is working on making the change. I'll write to you when we're ready to make the transition.

**Comment by Ardnived** [comment]
Completed
