### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#11]
In the footer of the website there is a piece of UI to switch between different languages. But this is a very simple implementation that won't scale for many languages.

Here is what it currently looks like:
<img width="1169" alt="Screenshot 2019-10-15 at 20 40 15" src="https://user-images.githubusercontent.com/1362167/66864041-35e26480-ef8c-11e9-8cb3-96db0b97d349.png">

And here is the design of what we want it to look like:
<img width="1293" alt="Screenshot 2019-10-17 at 15 34 17" src="https://user-images.githubusercontent.com/1362167/67018816-a8ba1f80-f0f3-11e9-8a14-f8d31c770b60.png">
This design shows a new world icon - ignore that, and instead use the world icon which is already present in the first screenshot. Also don't worry about changing the social media icons (which are currently different between the designs and the implementation).

When you click the world icon, it should open up a menu where all the languages are listed. Which should look like this on desktop. We'll probably want to add a drop shadow to that menu box as well.
![Screenshot 2020-07-01 at 08 06 26](https://user-images.githubusercontent.com/1362167/86213668-fa1b1980-bb71-11ea-8f32-6e47801ecea1.png)

On mobile we will likely want a full screen dropdown menu, but we can look at implementing that after the desktop version is working.

**Some tips**
 - If you go to `app/views/layouts/partials/_footer.html.slim`, line `51` you will find the place where the current language switcher is defined.
 - If you go to `app/assets/stylesheets/front/footer.sass`, line `158` you will find where the styles for the current language switcher are defined.
 - You will likely need to set up some new JavaScript to handle this language switcher, to do that you should
   - Create a new file called `language-switcher.js` in `app/assets/javascripts/front`
   - Add `Application.loadFirst('language', LanguageSwitcher)` to `app/assets/javascripts/front/application.js`
   - Add the `js-language` class to the language switcher HTML element.
   - Look at the other javascript files and follow the same patterns.
 - You can use this line of code to get the localized name of a language `I18nData.languages(locale)[locale.to_s.upcase].titleize` (where `locale` is something like `:en`, `:de`, etc)
 - You can get the list of languages which should appear in the language switcher with `Rails.configuration.published_locales`

**Comment by SanchitaV9** [comment]
Hi Devindra,

I started looking into the issue before sometime... could not start earlier
due to laptop issues.
I was installing Postgres and my laptop started getting hanged (since it is
quite old)  :(

Wanted to ask, when I need to run my code and see how it is working, what
all things would be required to be installed ? Or can directly run through
Github ?

Also I am not able to find the below file :
app/assets/stylesheets/front/footer.sass

Thanks,
Sanchita.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Ardnived** [comment]
@SanchitaV9 
The only things you will need installed on your computer as Postgres and Ruby 2.5.2, are you using a Windows or a Mac?

If you are using Mac, you can install Postgres.app, and you can install Ruby using RVM.
 - Postgres.app - https://postgresapp.com
 - RVM - https://rvm.io

If you are using windows you will have to do some research, since most command line tools don't work on Windows, I'm not sure how one installs those things. But Postgres and Ruby 2.5.2 are very common things to install it would be easy to find.

You can't run anything through GitHub, github just stores the code, once Postgres and Ruby are installed you need to open the command line and run the commands which I've noted here - https://github.com/sydevs/WeMeditate#setup

**Comment by SanchitaV9** [comment]
Hello Devindra,

Thanks for the details.

I have Windows os. I have installed postgres, will do some research for
Ruby and run the commands.

Also I am not able to find the below file :

app/assets/stylesheets/front/footer.sass


Thanks,
Sanchita.

**Comment by Ardnived** [comment]
@SanchitaV9 The footer.sass file is actually here
[app/assets/stylesheets/front/1_basics/footer.sass](https://github.com/sydevs/WeMeditate/blob/master/app/assets/stylesheets/front/1_basics/footer.sass)
