### ISSUE TITLE
Locale redirect and hreflang tag

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/WeMeditate#114]
We should serve the right language version of the site depending on the user location.
Like if you go to apple.com when you're in the UK, it redirects you go to apple.com/uk

Another thing about this: we need to implement hreflang tag for all the language versions:

https://developers.google.com/search/docs/advanced/crawling/localized-versions

https://moz.com/learn/seo/hreflang-tag

**Comment by dbackeus** [comment]
An easy and performant way to achieve user location handling would be to redirect based on the `CF-IPCountry` header passed by the Cloudflare proxy. The value of the header is a 2 letter country code based on the client IP-address (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

For unknown countries the value is `"xx"`.

Getting the header value from within Rails is done via eg. `country_code = request.headers["HTTP_CF_IPCOUNTRY"]`.

**Comment by Ardnived** [comment]
Excellent tip, thank you @dbackeus

**Comment by Ardnived** [comment]
@antontcymbal So I'm thinking what we should do is, automatically redirect only if you are on the English homepage, and if you are on any other page instead show a popup asking whether you prefer X other language.

Once a user responds to that popup once, we'll take that as their preference and always / never redirect that (unless they explicitly switch language from the footer).

Most users coming from Google should land on the correct page, assuming the hreflang works as intended. It's really just people who come from social media or posters that we need to target, and those people will almost always land on wemeditate.com

Maybe also on wemeditate.com/live and wemeditate.com/classes as well. We could also add those to the automatic redirect.

In other situations we may find an automatic redirect more disruptive than helpful.

**Comment by dbackeus** [comment]
Never worked with WhatsApp Business API. Judging by their marketing page for it (https://www.whatsapp.com/business/api) I would expect just getting access to be potentially expensive (makes it clear the target audience is "medium to large businesses" and no free sign up), but maybe I'm missing something.

With regards to SMS https://www.twilio.com is probably the most convenient service for that. I've done a basic SMS sending integration using that in the past and it's easy to get going. The cost will scale with number of subscribers though. Sending SMS, unlike email, has a base cost associated to it's never going to be ridiculously cheap.

Looks like Twilio integrates with WhatsApp Business API so potentially a good option for an all in one solution: https://www.twilio.com/whatsapp

Another approach for WhatsApp interaction might be to set up WhatsApp groups for programs and then use regular bots to send messages to those groups. I haven't built WhatsApp bots but I'm assuming it would be free (apart from hosting costs) similar to Slack / Telegram bots.

**Comment by dbackeus** [comment]
Oh, didn't realize WhatsApp didn't even have open bot support:
<img width="742" alt="Screenshot 2022-01-30 at 14 16 26" src="https://user-images.githubusercontent.com/3461/151701299-4eac101f-8dbf-4856-a732-b454b61e36e6.png">
(via https://botsociety.io/blog/2018/09/whatsapp-bot)

Not a big fan of WhatsApp and the ~~Facebook~~ Meta enterprise to be honest 😐

**Comment by Ardnived** [comment]
I'll implement a centred bottom popup with a prominent headline in the suggested language. Then we can play around with the design.

> **Are you looking for Russian?**
> Go to wemeditate.com/ru ->

**Comment by Ardnived** [comment]
This is now implemented, pending design review from @antontcymbal
