### ISSUE TITLE
Migrate Heroku servers to European region

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#125]
This will bring the servers closer to the center of our user base, and help calm yogis who have concerns about the servers being hosted in the US.

Instructions - https://devcenter.heroku.com/articles/app-migration

**Comment by Ardnived** [comment]
@dbackeus Do you have any insight or experience with this? Especially if you have any insight into GDPR data protection concerns with Heroku (or assurances about a lack thereof).

**Comment by dbackeus** [comment]
Even with EU based dynos Heroku still stores postgres backups in the US. Logplex (ie. all logging) is also routed via US.

There is also some extreme interpretations of GDPR which argues that no US-based company can be used at all, even if the data is in EU, since US government by law have the right to subpena and request personal data from any US-based company. This not only includes Heroku but all the big cloud providers.

If you want to go all in on "GDPR safe" hosting https://scalingo.com/ is a French almost carbon copy of Heroku.

With regards to migrating Heroku from EU to US it would be fairly straight forward and should be possible with 0 downtime as far as public pages goes. We would just have to shut down admin for some time to avoid data mutations to be able to migrate the data cleanly.

BTW what personal data do we store on wemeditate?

**Comment by Ardnived** [comment]
A good question about personal data. Actually this issue should have been posted on the Atlas repo - where we collect names and email addresses.

The only personal data that We Meditate collects is:
 - Google Analytics
 - Email subscriptions - but these are sent to Klaviyo immediately and not stored in the database. Klaviyo is also a US company.

I'll discuss this further with Anton, but I think (from our discussions with the UK yogis), we're going to take that stance that it's not a problem. And rely on 

Good to know about Scalingo, if it becomes necessary to switch.

**Comment by Ardnived** [comment]
This no longer seems necessary for now. European servers would be a bit more central to our user base, but Cloudflare means that wouldn't have any real effect on end users.

**Comment by dbackeus** [comment]
If we want to improve global performance could consider HTTP caching HTML responses via Cloudflare as well (not only static assets).

**Comment by Ardnived** [comment]
Ah right. I didn't realise that we only cache static assets on Cloudflare. I think that makes sense though. In that case, perhaps a migration does make sense.

**Comment by dbackeus** [comment]
It's a can of worms with amazing benefits though :)

I gave a presentation on a recent Ruby meetup in Stockholm. It's kind of 3 presentations in one. The third part talks about using Cloudflare for HTTP caching ActionController responses. Maybe of interest: https://images.auctionet.com/misc/shtmlrb20220309.mp4

**Comment by Ardnived** [comment]
Hm, well I'm definitely not against it in principle. It's just something I lack the time to really deal with. What would you say is the potential downside, if any? Is there a cost associated with it?

I skimmed through the later part of the video, though I haven't watched it all at the moment.

I like this approach you mention here, when anything changes just purge everything that could be related, rather than trying to get granular. We often have trouble at my work with having many levels of caching and often very specific caching that causes confusion for the website writers/admins. Or the header and footer being cached separately and not getting refreshed. That's the kind of stuff, I'm keen to avoid. Especially an increase in support requests due to confusion over the cache not being reflected.

I noticed that you also disabled the cache for anyone logged in, which would likely solve that for us too. The problem with WEF (my work) is that the WEB and CMS are totally separate websites, so admins/writers are never logged in on the front end.

**Comment by Ardnived** [comment]
No, we don't have any personalised content. So that's not strictly a problem, it would have just been useful to avoid complaints from editors, if the cache purge logic failed.

Okay. Well I'm convinced it would be a good idea, but not something I could commit time to right now, myself - with the other outstanding We Meditate and Sahaj Atlas work.

**Comment by dbackeus** [comment]
Makes sense 👍 

Not impossible that I could get some time off and take a stab at it at some point.

**Comment by Ardnived** [comment]
Closing this ticket in favour of https://github.com/sydevs/WeMeditate/issues/143
