### ISSUE TITLE
Klaviyo account suspended

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#140]
Looks like our payment lapsed on Klaviyo, so emails are no longer being sent.

We need to fix that, and maybe also briefly discuss the plan for the We Meditate app, and whether we might want to consider switching to an alternative provider.

**Comment by dbackeus** [comment]
How much email are we sending? Do we need any particular features or is it just raw ActionMailer type stuff?

I've heard very good things about postmark.com. Also had some good experiences with mailgun.com but looks like they no longer offer a perpetual free plan, only 3 month trial.

**Comment by Ardnived** [comment]
We have about 1800 contact, and I think we send up to 5000 emails a month. Those two services don't look like they'd work for our needs though - they're for transactional emails, but we need a mailing list manager, like MailChimp.

It's currently used to send reminders to users that subscribe for live events. It has also been used to send a weekly limited-run meditation course, and in the future might be used for a newsletter of some kind.

**Comment by Ardnived** [comment]
The Klaviyo account is in good standing again.
