### ISSUE TITLE
Continuous integration / deployment

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#15]
We could set up automatic rubocop validation and unit testing for any PR request to master. This would help catch some errors early on, and strongly enforce rubocop validations.

In addition we could set up the master branch to actually precompile assets and deploy new versions to Heroku automatically. This would mean new versions can be deployed without access to Heroku, and also help avoid the occasional issue that occurs where assets take a long time to compile, and the end user sees a page lacking CSS.

**Comment by dbackeus** [comment]
So linting is done and testing will be done as soon as https://github.com/sydevs/WeMeditate/pull/38 is approved.

I'm not sure what the asset precompilation paragraph means exactly.
Are we not following the conventional pre-compilation of assets during the heroku build phase already?
Does "without access to heroku" imply enabling herokus automatic deploys on a given branch or something else?

**Comment by Ardnived** [comment]
> I'm not sure what the asset precompilation paragraph means exactly.
Yeah, don't worry about that.

> Also not sure what "without access to heroku" is referring to... just to be able to deploy branches without having a heroku account (e.g. by enabling automatic deploys for the master branch)?
Yes, I've already implemented that since I wrote this ticket.

**Comment by Ardnived** [comment]
Seems like this is basically done, we just need to set up the Hound and Travis CI accounts so that I and later others can manage them. The idea has been that all services should be registered to the sydevelopers email address so that we can get access to them by one route, and centralise billing.

**Comment by dbackeus** [comment]
I believe no team management is necessary. Try logging in to travis / hound with your GitHub and you might be able to administrate out of the box. The actual integration happens via GitHub apps installed on the sydevs org.

**Comment by Ardnived** [comment]
Note for the future: Currently the Travis CI configuration is messed up. Will need to fix that, then close this ticket.

**Comment by dbackeus** [comment]
Fix at https://github.com/sydevs/WeMeditate/pull/69
