### ISSUE TITLE
Handle unsupported browsers

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#17]
We only support the latest versions of Chrome, Safari, Firefox, Edge, and Opera. It is also expected that most other mobile browsers will be reasonably compatible, but they don't have enough market share to actually test on.

It might be worthwhile to show a banner or a redirect for older browsers, especially Internet Explorer and Safari, which have poor compliance.

We already have [a gem](https://github.com/fnando/browser) integrated which can help us to detect "modern" browsers.

**Comment by Sushil-Kumar1999** [comment]
I think I can do this.

**Comment by Ardnived** [comment]
Hey @Sushil-Kumar1999, before implementing this, I think we need some thoughts on the design or how this would look from @antontcymbal. We probably need a design first.

**Comment by Ardnived** [comment]
Internet Explorer was the main culprit that people might have been holding on to. Internet Explorer no longer has an appreciable market share.

This banner will rarely inform people of something useful, and will complicate the interface (competing with other popups like language redirect, cookie consent, and possibly contact form).

It no longer seems necessary to implement this.
