### ISSUE TITLE
Precompile error pages

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#28]
Currently our error pages (404, 500, etc) are rendered dynamically whenever an error occurs. This can be an issue if an error occurs during the rendering of the error page.

The normal solution to this is to include state HTML files in the `/public` folder. But the issue with this is that then those HTML files will not respond to changes to the source code of the header and footer.

The solution to this would be to find a solution to precompile those error pages and place them in the public folder. The key challenge for this is that we need a different set of error pages for each language.

Here is a gem which supports pre-compilation, but it doesn't support localisation. It sounds though like it wouldn't be too difficult to add this and submit a pull request.
https://github.com/bronson/error_page_assets

**Comment by Mrinalsinghal** [comment]
With the current Webpacker branch, we are using `stylesheet_packs_with_chunks_tag / javascript_packs_with_chunks_tag` which `rails assets:precompile` does not accept. It only includes stylesheets and javascripts if added with `stylesheet_link_tag / javascript_include_tag`.

**Comment by Ardnived** [comment]
This was resolved by https://github.com/sydevs/WeMeditate/pull/97
