### ISSUE TITLE
Vimeo blocked in Indonesia and China

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#32]
There are already seekers in Indonesia who have reported not being able to access videos. Maybe we can route the video requests through our own servers (caching a version of the video in Rails) to avoid this, but that might be very costly.

A temporary measure would be to detect countries where Vimeo is banner and display a message instructing them to use a VPN if they want to access the meditations.

**Comment by amrutadotorg** [comment]
Hi. On Amruta we use youku. http://i.youku.com/i/UMTIwMjM1MTEyOA==
See also Cloudflare streaming https://www.cloudflare.com/products/stream-delivery/ 
pricing: 
Streaming: $1 per thousand minutes viewed
Storage: $5 per thousand minutes of video stored

**Comment by Ardnived** [comment]
I was recently considering switching We Meditate to https://www.jwplayer.com because it would able to consolidate several different services we use (Vimeo, Restream, Twitch, and our js video player). But I'm not yet sure if it's available in those countries.

Does youku have any documentation in English?

**Comment by amrutadotorg** [comment]
If you want to use the API the docs are here.
https://cloud.youku.com/docs <https://cloud.youku.com/docs>
1-2 years ago there is an English page but it is no more.
For limited number of videos it is better to upload the videos directly via the uploader.

Ask someone from China to create an account for you (verification is done via the mobile China number).

**Comment by Ardnived** [comment]
If there is no english documentation then I doubt we will try to use it. I'd prefer to find some other video service which has English documentation but works in China.

**Comment by Ardnived** [comment]
We're now planning to replace Vimeo with JWPlayer, which would solve the problem. https://github.com/sydevs/WeMeditate/issues/124
