### ISSUE TITLE
Broken error state when providing non existing Vimeo ID in admin

### ISSUE THREAD

**Issue by dbackeus** [sydevs/WeMeditate#54]
When providing the vimeo input fields with a non-existing ID they end up displaying an infinite spinner indicating that something is waiting to load while in reality the request handling code has raised an exception.

Screenshot:
<img width="932" alt="Screenshot 2020-05-06 at 18 22 12" src="https://user-images.githubusercontent.com/3461/81202197-8a9c0a00-8fc6-11ea-9e65-bd2d6e6d1a10.png">

**Comment by Ardnived** [comment]
Vimeo videos are no longer supported, and this interface has been disabled - to be removed entirely. So this issue can no longer occur.
