### ISSUE TITLE
header.learn_more I18n key not suitable for cookie banner in Swedish

### ISSUE THREAD

**Issue by dbackeus** [sydevs/WeMeditate#56]
The `header.learn_more` translation key is used both for the navbar and cookie banner:

<img width="1317" alt="Screenshot 2020-05-08 at 14 28 22" src="https://user-images.githubusercontent.com/3461/81405766-97406f80-9138-11ea-95b6-df4e2b625618.png">

In Swedish it's not suitable to have the same phrasing for both (the one for cookie banner should state the equivalent of "Read more" rather than "Learn more"). So would be nice if we could split this up.

Side note: Maybe cookie stuff should be broken out of the `header` namespace altogether... I wasn't expecting the correlation since the cookie banner is visually at the bottom of the page.

**Comment by Ardnived** [comment]
This has been changed in this commit: https://github.com/sydevs/WeMeditate/commit/a0e5a9d5d3b5b9380ea4969b8267b4f534f1cd48

Sorry, we totally could have got this done earlier, but I didn't see this issue until now. Feel free to tag me on issues in the future if you want me to look at them.
