### ISSUE TITLE
Broken mobile menu (on some screens)

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/WeMeditate#75]
Remove "follow us" from the mobile menu, make the menu items centered horizontally, and also couldthe distance between the social icons and the last menu item "About meditation" could be a set in % ? 

Like so: https://invis.io/T5Z4PZIXWH6

Otherwise, there are issues with the menu on some screens:
Iphone se (1st) 13.1.2
https://www.loom.com/share/5e0480a53a2a448fa6de549372418120?from_recorder=1

In particular, not the whole of the menu fits, and also there's some issue with the scrolling.

**Comment by Ardnived** [comment]
Fixed by commit https://github.com/sydevs/WeMeditate/commit/ab730786b08b1649c77e5fd3fed0e47def003b6c
