### ISSUE TITLE
Overhaul content editor

### ISSUE THREAD

**Issue by Ardnived** [sydevs/WeMeditate#81]
There are several issues with the content editor

### Features
- [x] Table of Contents block
- [x] References / bibliography block (how can we make it easy to link to?)
- [x] Callout blocks need titles
- [x] Audio block (including an album mode)
- [x] Auto-saving (?)
- [ ] The video block should support YouTube embeds

### Bugs & Changes
- [x] Copying and pasting text is frequently frustrating. It often creates new blocks instead of pasting into the block at hand
- [x] It's not possible to include formatting or links in many of the block types
- [x] There are too many types of blocks - it's overwhelming to work with.
- [ ] Videos need to be changed to work with JW Player
- [x] We Meditate content (articles, meditations) need to be listable and not just in a gallery mode.
- [x] When an image upload fails, the whole page is locked and you lose all your edits.
- [x] Support for GIFs
- [x] Remove references to assets.wemeditate.co and wemeditate.co in the text.

**Comment by NooriaTcymbal** [comment]
When you select the 'Light' option of a Splash Screen in the 'Textbox' block, if you start entering text before you upload an image you can't actually see the text as it's white-on-white. Is there a way the writing can still appear in black if there isn't an image yet? Just to avoid confusion.
<img width="842" alt="Screen Shot 2021-09-22 at 10 30 01" src="https://user-images.githubusercontent.com/91188796/134319609-5f542443-6ae5-4e83-bcba-cc5e67bc9be9.png">

<img width="859" alt="Screen Shot 2021-09-22 at 10 30 50" src="https://user-images.githubusercontent.com/91188796/134319528-688a994f-324a-45a7-871d-db1d8e0485b0.png">

**Comment by NooriaTcymbal** [comment]
When toggling between different types of a certain block, the name of the type doesn't always change. Sometimes does, sometimes doesn't.

https://gyazo.com/9f029e681bb8bb6c1639bd1813ba1098

**Comment by NooriaTcymbal** [comment]
When adding We Meditate content, search appears to work for techniques but not for articles or meditations.

Articles: https://gyazo.com/c0e37d2d5c78a5d14e33386777d7a4b7

Techniques: https://gyazo.com/e6b8b1dfe09060114fc1485d59d9d7cf

Meditations: https://gyazo.com/bb779c41766f3440e3e4f35abf9d0dc8

**Comment by NooriaTcymbal** [comment]
The 'gradient' option on white space doesn't seem to work. If you select it, no gradient shows up on the webpage preview, just white space.

**Comment by NooriaTcymbal** [comment]
Getting an error message when trying to view a splashback block on preview.
<img width="1279" alt="Screen Shot 2021-09-22 at 12 10 39" src="https://user-images.githubusercontent.com/91188796/134333509-e2b49724-9d94-40fd-927f-c39bc30fa14b.png">

**Comment by NooriaTcymbal** [comment]
If you try to copy and paste multiple paragraphs into a list with the intention of each paragraph being a point on the list, this doesn't work. It simply gets pasted as a regular text block beneath the list. Therefore, you have to copy and paste each paragraph separately into the list. This isn't the end of the world, and in some cases maybe you anyways would want to have multiple paragraphs in one point on the list, but thought I would mention.
https://gyazo.com/1068359b2f8aca1e856ad064aeac2933

**Comment by NooriaTcymbal** [comment]
When you add a link to text in a list, it publishes the html rather than hyperlinked text.
https://gyazo.com/0cf66fe22d52c0eceb8ea36612f233fd

**Comment by Ardnived** [comment]
> If you try to copy and paste multiple paragraphs into a list with the intention of each paragraph being a point on the list, this doesn't work. It simply gets pasted as a regular text block beneath the list. Therefore, you have to copy and paste each paragraph separately into the list. This isn't the end of the world, and in some cases maybe you anyways would want to have multiple paragraphs in one point on the list, but thought I would mention. https://gyazo.com/1068359b2f8aca1e856ad064aeac2933

Unfortunately there's no good solution to this. At least not with some much deeper time-consuming work. What you can also  do is just press delete at the start of the first paragraph and it should more the paragraph into the list element, like how most text editors work.

**Comment by Ardnived** [comment]
> When toggling between different types of a certain block, the name of the type and the options for that type doesn't always change. Sometimes does, sometimes doesn't. Maybe it's the case that when you've already inserted some content for one type this bug occurs..
> 
> https://gyazo.com/9f029e681bb8bb6c1639bd1813ba1098

This is not fixed yet, but I was having trouble reproducing it. I was able to at first and then the issue disappeared. Will look at it further in the future.

**Comment by NooriaTcymbal** [comment]
> When toggling between different types of a certain block, the name of the type and the options for that type doesn't always change. Sometimes does, sometimes doesn't. Maybe it's the case that when you've already inserted some content for one type this bug occurs..
> 
> https://gyazo.com/9f029e681bb8bb6c1639bd1813ba1098

For me this error is still occurring:
https://gyazo.com/65acf117c118f84601f347b729b7a835
https://gyazo.com/3f52949daaebc647ae81153c686432d3

**Comment by NooriaTcymbal** [comment]
> When adding We Meditate content, search appears to work for techniques but not for articles or meditations.
> 
> Articles: https://gyazo.com/c0e37d2d5c78a5d14e33386777d7a4b7
> 
> Techniques: https://gyazo.com/e6b8b1dfe09060114fc1485d59d9d7cf
> 
> Meditations: https://gyazo.com/bb779c41766f3440e3e4f35abf9d0dc8

For me this error is still occurring:
https://gyazo.com/65acf117c118f84601f347b729b7a835
https://gyazo.com/3f52949daaebc647ae81153c686432d3

**Comment by NooriaTcymbal** [comment]
Strange error message appears when on published page with a message submission form. 
https://gyazo.com/1087c809c731130efe226ab83be1207f

**Comment by NooriaTcymbal** [comment]
For the 'poem' option in textbox, when I try to start a new paragraph in the main text of the poem (as you would think one would have many new lines in a poem) by pressing the return key the cursor moves down, but then when I start typing the text appears in the original line.
https://gyazo.com/78e8412d01421836ad5a0f298a9fe3df

**Comment by NooriaTcymbal** [comment]
For the option of a textbox appearing on top of an image, when published only the image seems to show up, with no textbox. Is this to do with the size of the image maybe?
https://gyazo.com/24ad336f8b7256aa1cbc2722e56333c6

**Comment by NooriaTcymbal** [comment]
All of the gradient colour options for a gradient on the 'Ornate' option for textbox with image (orange, blue, grey) show up the same, like this https://gyazo.com/238481af607702151eed5101a9ad3427. That said, how had you intended this to look, given that there is already a brown background to this block? Is the gradient supposed to appear after the block? (because that doesn't happen).

**Comment by NooriaTcymbal** [comment]
For some reason when uploading images for the 'column' option of layout block, there is no option to add more images to the third column https://gyazo.com/aecb51e72b104b34c01a7a904af53703

**Comment by NooriaTcymbal** [comment]
Pretty major problems with all the Layout block options.

I made a test of all three options, and firstly when I save suddenly all the text I enter for the titles disappear. This happens in all three versions (grid, accordion, column). 

As far as how they appear on the page...
Grid: appears as one weird line of overlapping text
Accordion: doesn't appear at all
Column: The titles have disappeared, and initially the text was showing up in the same weird line as the grid option, but then when I changed the text it became normal..haven't been able to reproduce that error.

https://gyazo.com/532295fa549b47885b0d257b0f9410c8

**Comment by Ardnived** [comment]
> Strange error message appears when on published page with a message submission form. https://gyazo.com/1087c809c731130efe226ab83be1207f

This is just because the ReCaptcha isn't configured to work on the staging server. It will work fine in production.

**Comment by Ardnived** [comment]
> > When adding We Meditate content, search appears to work for techniques but not for articles or meditations.
> > Articles: https://gyazo.com/c0e37d2d5c78a5d14e33386777d7a4b7
> > Techniques: https://gyazo.com/e6b8b1dfe09060114fc1485d59d9d7cf
> > Meditations: https://gyazo.com/bb779c41766f3440e3e4f35abf9d0dc8
> 
> For me this error is still occurring: https://gyazo.com/65acf117c118f84601f347b729b7a835 https://gyazo.com/3f52949daaebc647ae81153c686432d3

This was occurring because you weren't searching for the articles / meditations which exist on the staging server.

**Comment by Ardnived** [comment]
> For some reason when uploading images for the 'column' option of layout block, there is no option to add more images to the third column https://gyazo.com/aecb51e72b104b34c01a7a904af53703

You should actually only be able to add 1 image per item. Which will now be fixed.

**Comment by Ardnived** [comment]
The remaining tasks are addressed now in their own issues.
