### ISSUE TITLE
Make the Google Search Console accept our sitemap

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/WeMeditate#83]
It is a best practice to have a valid sitemap. We currently generate a new sitemap on a nightly basis, however Google Search Console has so far been unable to properly parse the sitemap. Someone needs to log in to Google Search Console, submit the sitemap and see what the errors are, then go about fixing them. This will also involve looking at our code which generates the sitemap and the library that we use to do that sitemap generation and compression.

**Comment by Ardnived** [comment]
On further inspection Google has been using our sitemap for sometime, but various other issues with the sitemap were discovered and fixed.
