### ISSUE TITLE
"Save draft" button doesn't actually save changes

### ISSUE THREAD

**Issue by fhjgch** [sydevs/WeMeditate#95]
When making changes to content in the admin page (`admin.wemeditate.com`), I realized that hitting "Save Draft" button doesn't actually save the content. Only "Save & approve" saves the changes.

These are the buttons:
![image](https://user-images.githubusercontent.com/46992955/119559961-9f9b3500-bda3-11eb-823b-f25540ae755c.png)

**Comment by Ardnived** [comment]
This appears to be fixed, as I've been using the function myself without issue lately.
@fhjgch Can you let me know if the issue still occurs for you?

I thought it could be a permission issue for regional admins (which is what you are), but it works for me when I login as a regional admin as well.
