### ISSUE TITLE
Deleting a main page redirects back to the deleted page

### ISSUE THREAD

**Issue by dbackeus** [sydevs/WeMeditate#96]
While testing out the migration of images from assets.wemeditate.co to assets.wemeditate.com I created a temporary draft main page to test out image uploading. After deleting it I was redirected back to the deleted page which resulted in a 404:

<img width="899" alt="Screenshot 2021-06-28 at 14 55 20" src="https://user-images.githubusercontent.com/3461/123639841-dd66ff80-d820-11eb-8090-39d850ff4756.png">

**Comment by dbackeus** [comment]
Another odd thing: Apparently the page preview is still accessible: https://admin.wemeditate.com/en/static_pages/31/preview

So I guess we're doing a soft delete. Maybe the preview page should also take the deleted state into consideration.

**Comment by Ardnived** [comment]
Haha, I clicked that preview link to take a look, and at first I thought you had trolled me by linking to something else because of the splash image you set.

I don't think we are doing any soft deletion.

**Comment by dbackeus** [comment]
Haha, I just used some random meme pictures I had lying around my Pictures folder while trying out the asset migration ;)

**Comment by Ardnived** [comment]
Seems like this issue is no longer occurring. Or at least I can't reproduce it. I was able to delete both locally and on the server. It seems that the test page you created was never deleted, but I was able to delete it.
